---
- name: Install Cuckoo into virtualenv - {{ cuckoo_dir }}
  become: true
  become_method: sudo
  pip: name={{ item }} state=latest virtualenv="{{ cuckoo_dir }}"
  with_items:
    - pip
    - setuptools
    - psycopg2
    - cuckoo

- name: Change owner of {{ cuckoo_dir }} directory
  become: true
  become_method: sudo
  file:
    path: "{{ cuckoo_dir }}"
    state: directory
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    recurse: true

- name: Setup Cuckoo Working Directory - {{ cwd }}
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  command: "{{ cuckoo_dir }}/bin/cuckoo --cwd {{ cwd }}"
  failed_when: result.rc != 1 and result.rc != 0
  register: result

- name: Check if {{ cuckoo_conf }} exists
  stat:
    path: "{{ cwd }}/conf/{{ cuckoo_conf }}.conf"
  register: file_exist

- name: Backup of {{ cuckoo_conf }}
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  command: mv "{{ cwd }}/conf/{{ cuckoo_conf }}.conf" "{{ cwd }}/conf/{{ cuckoo_conf }}.conf.original"
  when: file_exist.stat.exists

- name: Copy local Cuckoo configuration files to {{ cwd }}/conf
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ cwd }}/conf"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644
  with_fileglob:
    - ../files/*

- name: Copy local Cuckoo routing.conf file to {{ cwd }}/conf
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  template:
    src: routing.conf
    dest: "{{ cwd }}/conf"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644

- name: Install Cuckoo signature modules
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  command: "{{ cuckoo_dir }}/bin/cuckoo community"
  failed_when: result.rc != 1 and result.rc != 0
  register: result

- name: Disable AppArmor profile for Tcpdump in Ubuntu
  become: true
  become_method: sudo
  shell: aa-disable /usr/sbin/tcpdump
  ignore_errors: true

- name: Set specific Linux capabilities to the Tcpdump binary
  become: true
  become_method: sudo
  shell: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump
