---
#- name: Enable i386 architecture for libc6:i386 support
#  command: dpkg --add-architecture i386

- name: Enable i386 architecture for packages
  become: true
  become_method: sudo
  apt:
    update_cache: yes
    dpkg_options: 'add-architecture i386'


- name: Install "{{ ubuntu_package }}"
  become: true
  become_method: sudo
  apt:
    pkg: "{{ ubuntu_package }}"
    state: present
    update_cache: false
