---
- name: Reboot server
  become: true
  become_method: sudo
  shell: reboot
  async: 0
  poll: 0

- name: Waiting for server to come back
  local_action: wait_for host={{ ansible_host }} state=started

- name: Set ip of vmnet{{ vmwareNetworkAdaoter }}
  become: true
  become_method: sudo
  command: ifconfig vmnet{{ vmwareNetworkAdapter }} 192.168.56.1 netmask 255.255.255.0 broadcast 192.168.56.255 up

- name: Change owner of /var/run/suricata folder
  become: true
  become_method: sudo
  file:
    path: "/var/run/suricata"
    state: directory
    recurse: true
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0775

- name: Start Suricata IDS
  become: true
  become_method: sudo
  shell: suricata -D --user=cuckoo --group=cuckoo --unix-socket=cuckoo.socket

- name: Wait for Suricata IDS
  pause:
    minutes: 1

- name: Start Moloch capture
  become: true
  become_method: sudo
  shell: systemctl start molochcapture.service

- name: Start Moloch viewer
  become: true
  become_method: sudo
  shell: systemctl start molochviewer.service

- name: Wait for Moloch
  pause:
    minutes: 1

- name: Start Cuckoo Rooter
  become: true
  become_method: sudo
  shell: "{{ cuckoo_dir }}/bin/cuckoo rooter &"

- name: Wait for Rooter
  pause:
    minutes: 1

- name: Start Cuckoo Django Web Interface
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: "nohup {{ cuckoo_dir }}/bin/cuckoo web runserver 0.0.0.0:8880 >/dev/null 2>&1 &"

- name: Wait for Cuckoo Web
  pause:
    minutes: 1

- name: Start Cuckoo API
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: "nohup {{ cuckoo_dir }}/bin/cuckoo api --host 0.0.0.0 --port 8881 >/dev/null 2>&1 &"

- name: Wait for Cuckoo API
  pause:
    minutes: 1

- name: Start Cuckoo Sandbox
  become: true
  become_method: sudo
  become_user: "{{ cuckoo_user }}"
  shell: "nohup {{ cuckoo_dir }}/bin/cuckoo -d >/dev/null 2>&1 &"
